/**
 * Supabase Database Types
 *
 * This file will be auto-generated by the Supabase CLI once the database schema is created.
 * For now, it provides a placeholder type structure for development.
 *
 * To generate actual types after database setup:
 * 1. Install Supabase CLI: npm install -g supabase
 * 2. Login: supabase login
 * 3. Generate types: supabase gen types typescript --project-id [your-project-id] > types/supabase.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // User profiles extending Supabase auth
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          full_name: string | null
          avatar_url: string | null
          subscription_tier: 'free' | 'pro' | 'enterprise'
          subscription_status: 'active' | 'inactive' | 'cancelled'
        }
        Insert: {
          id: string
          created_at?: string
          updated_at?: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          subscription_tier?: 'free' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'inactive' | 'cancelled'
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          subscription_tier?: 'free' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'inactive' | 'cancelled'
        }
      }

      // Brands
      brands: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          name: string
          description: string | null
          logo_url: string | null
          website_url: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          name: string
          description?: string | null
          logo_url?: string | null
          website_url?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          name?: string
          description?: string | null
          logo_url?: string | null
          website_url?: string | null
          is_active?: boolean
        }
      }

      // Brand Brain context store
      brand_context: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          brand_name: string
          brand_voice: Json
          brand_values: string[]
          target_audience: Json
          content_pillars: string[]
          visual_identity: Json
          competitors: string[]
          unique_selling_points: string[]
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          brand_name: string
          brand_voice?: Json
          brand_values?: string[]
          target_audience?: Json
          content_pillars?: string[]
          visual_identity?: Json
          competitors?: string[]
          unique_selling_points?: string[]
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          brand_name?: string
          brand_voice?: Json
          brand_values?: string[]
          target_audience?: Json
          content_pillars?: string[]
          visual_identity?: Json
          competitors?: string[]
          unique_selling_points?: string[]
        }
      }

      // Social media accounts
      social_accounts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          platform: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id: string
          account_name: string
          access_token: string
          refresh_token: string | null
          token_expires_at: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          platform: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id: string
          account_name: string
          access_token: string
          refresh_token?: string | null
          token_expires_at?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          platform?: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id?: string
          account_name?: string
          access_token?: string
          refresh_token?: string | null
          token_expires_at?: string | null
          is_active?: boolean
        }
      }

      // Content posts
      posts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          content_text: string
          content_images: string[]
          platforms: string[]
          status: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for: string | null
          published_at: string | null
          ai_generated: boolean
          engagement_metrics: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          content_text: string
          content_images?: string[]
          platforms: string[]
          status?: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for?: string | null
          published_at?: string | null
          ai_generated?: boolean
          engagement_metrics?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          content_text?: string
          content_images?: string[]
          platforms?: string[]
          status?: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for?: string | null
          published_at?: string | null
          ai_generated?: boolean
          engagement_metrics?: Json | null
        }
      }

      // n8n workflow executions
      workflow_executions: {
        Row: {
          id: string
          user_id: string
          created_at: string
          workflow_id: string
          workflow_name: string
          status: 'running' | 'completed' | 'failed'
          input_data: Json
          output_data: Json | null
          error: string | null
          started_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          workflow_id: string
          workflow_name: string
          status?: 'running' | 'completed' | 'failed'
          input_data: Json
          output_data?: Json | null
          error?: string | null
          started_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          workflow_id?: string
          workflow_name?: string
          status?: 'running' | 'completed' | 'failed'
          input_data?: Json
          output_data?: Json | null
          error?: string | null
          started_at?: string
          completed_at?: string | null
        }
      }

      // User roles for authorization
      user_roles: {
        Row: {
          id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }

      // Subscription plans
      subscription_plans: {
        Row: {
          id: string
          plan_id: 'free' | 'starter' | 'growth' | 'agency'
          name: string
          description: string | null
          stripe_price_id: string | null
          stripe_product_id: string | null
          price_monthly_cents: number
          price_yearly_cents: number | null
          currency: string
          limits: Json
          is_active: boolean
          display_order: number
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          plan_id: 'free' | 'starter' | 'growth' | 'agency'
          name: string
          description?: string | null
          stripe_price_id?: string | null
          stripe_product_id?: string | null
          price_monthly_cents: number
          price_yearly_cents?: number | null
          currency?: string
          limits: Json
          is_active?: boolean
          display_order?: number
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          plan_id?: 'free' | 'starter' | 'growth' | 'agency'
          name?: string
          description?: string | null
          stripe_price_id?: string | null
          stripe_product_id?: string | null
          price_monthly_cents?: number
          price_yearly_cents?: number | null
          currency?: string
          limits?: Json
          is_active?: boolean
          display_order?: number
          created_at?: string
          updated_at?: string
        }
      }

      // User subscriptions
      subscriptions: {
        Row: {
          id: string
          user_id: string
          stripe_customer_id: string
          stripe_subscription_id: string | null
          stripe_price_id: string | null
          plan_id: 'free' | 'starter' | 'growth' | 'agency'
          status: string
          current_period_start: string
          current_period_end: string
          cancel_at_period_end: boolean
          canceled_at: string | null
          trial_start: string | null
          trial_end: string | null
          latest_invoice_id: string | null
          default_payment_method: string | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          stripe_customer_id: string
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          plan_id?: 'free' | 'starter' | 'growth' | 'agency'
          status?: string
          current_period_start?: string
          current_period_end?: string
          cancel_at_period_end?: boolean
          canceled_at?: string | null
          trial_start?: string | null
          trial_end?: string | null
          latest_invoice_id?: string | null
          default_payment_method?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          stripe_customer_id?: string
          stripe_subscription_id?: string | null
          stripe_price_id?: string | null
          plan_id?: 'free' | 'starter' | 'growth' | 'agency'
          status?: string
          current_period_start?: string
          current_period_end?: string
          cancel_at_period_end?: boolean
          canceled_at?: string | null
          trial_start?: string | null
          trial_end?: string | null
          latest_invoice_id?: string | null
          default_payment_method?: string | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }

      // Invoices
      invoices: {
        Row: {
          id: string
          user_id: string
          subscription_id: string | null
          stripe_invoice_id: string
          stripe_customer_id: string
          amount_due: number
          amount_paid: number
          currency: string
          status: string
          period_start: string
          period_end: string
          hosted_invoice_url: string | null
          invoice_pdf_url: string | null
          payment_intent_id: string | null
          paid_at: string | null
          attempt_count: number
          next_payment_attempt: string | null
          last_finalization_error: Json | null
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          subscription_id?: string | null
          stripe_invoice_id: string
          stripe_customer_id: string
          amount_due: number
          amount_paid: number
          currency: string
          status: string
          period_start: string
          period_end: string
          hosted_invoice_url?: string | null
          invoice_pdf_url?: string | null
          payment_intent_id?: string | null
          paid_at?: string | null
          attempt_count?: number
          next_payment_attempt?: string | null
          last_finalization_error?: Json | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          subscription_id?: string | null
          stripe_invoice_id?: string
          stripe_customer_id?: string
          amount_due?: number
          amount_paid?: number
          currency?: string
          status?: string
          period_start?: string
          period_end?: string
          hosted_invoice_url?: string | null
          invoice_pdf_url?: string | null
          payment_intent_id?: string | null
          paid_at?: string | null
          attempt_count?: number
          next_payment_attempt?: string | null
          last_finalization_error?: Json | null
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }

      // Webhook events
      webhook_events: {
        Row: {
          id: string
          stripe_event_id: string
          event_type: string
          event_data: Json
          processed: boolean
          processed_at: string | null
          processing_attempts: number
          error_message: string | null
          error_stack: string | null
          api_version: string | null
          request_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          stripe_event_id: string
          event_type: string
          event_data: Json
          processed?: boolean
          processed_at?: string | null
          processing_attempts?: number
          error_message?: string | null
          error_stack?: string | null
          api_version?: string | null
          request_id?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          stripe_event_id?: string
          event_type?: string
          event_data?: Json
          processed?: boolean
          processed_at?: string | null
          processing_attempts?: number
          error_message?: string | null
          error_stack?: string | null
          api_version?: string | null
          request_id?: string | null
          created_at?: string
          updated_at?: string
        }
      }

      // Usage metrics
      usage_metrics: {
        Row: {
          id: string
          user_id: string
          subscription_id: string | null
          period_start: string
          period_end: string
          posts_created: number
          posts_scheduled: number
          posts_published: number
          ai_credits_consumed: number
          ai_image_generations: number
          ai_content_generations: number
          brands_created: number
          social_accounts_connected: number
          storage_bytes: number
          media_files_count: number
          api_calls: number
          webhook_calls: number
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          subscription_id?: string | null
          period_start: string
          period_end: string
          posts_created?: number
          posts_scheduled?: number
          posts_published?: number
          ai_credits_consumed?: number
          ai_image_generations?: number
          ai_content_generations?: number
          brands_created?: number
          social_accounts_connected?: number
          storage_bytes?: number
          media_files_count?: number
          api_calls?: number
          webhook_calls?: number
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          subscription_id?: string | null
          period_start?: string
          period_end?: string
          posts_created?: number
          posts_scheduled?: number
          posts_published?: number
          ai_credits_consumed?: number
          ai_image_generations?: number
          ai_content_generations?: number
          brands_created?: number
          social_accounts_connected?: number
          storage_bytes?: number
          media_files_count?: number
          api_calls?: number
          webhook_calls?: number
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
    }

    Views: {
      // Add views here as needed
    }

    Functions: {
      // Check if user can perform an action based on usage limits
      check_usage_allowed: {
        Args: {
          p_user_id: string
          p_action: string
        }
        Returns: {
          allowed: boolean
          current_usage: number
          limit: number
          percentage_used: number
          message: string
        }[]
      }
      // Get subscription plan limits for a user
      get_subscription_limits: {
        Args: {
          p_user_id: string
        }
        Returns: {
          limits: Json
        }[]
      }
      // Update usage metrics
      update_usage_metric: {
        Args: {
          p_user_id: string
          p_metric: string
          p_amount: number
        }
        Returns: void
      }
    }

    Enums: {
      // Add custom enums here as needed
    }

    CompositeTypes: {
      // Add composite types here as needed
    }
  }
}
