/**
 * Supabase Database Types
 *
 * This file will be auto-generated by the Supabase CLI once the database schema is created.
 * For now, it provides a placeholder type structure for development.
 *
 * To generate actual types after database setup:
 * 1. Install Supabase CLI: npm install -g supabase
 * 2. Login: supabase login
 * 3. Generate types: supabase gen types typescript --project-id [your-project-id] > types/supabase.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // User profiles extending Supabase auth
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          full_name: string | null
          avatar_url: string | null
          subscription_tier: 'free' | 'pro' | 'enterprise'
          subscription_status: 'active' | 'inactive' | 'cancelled'
        }
        Insert: {
          id: string
          created_at?: string
          updated_at?: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          subscription_tier?: 'free' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'inactive' | 'cancelled'
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          subscription_tier?: 'free' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'inactive' | 'cancelled'
        }
      }

      // Brand Brain context store
      brand_context: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          brand_name: string
          brand_voice: Json
          brand_values: string[]
          target_audience: Json
          content_pillars: string[]
          visual_identity: Json
          competitors: string[]
          unique_selling_points: string[]
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          brand_name: string
          brand_voice?: Json
          brand_values?: string[]
          target_audience?: Json
          content_pillars?: string[]
          visual_identity?: Json
          competitors?: string[]
          unique_selling_points?: string[]
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          brand_name?: string
          brand_voice?: Json
          brand_values?: string[]
          target_audience?: Json
          content_pillars?: string[]
          visual_identity?: Json
          competitors?: string[]
          unique_selling_points?: string[]
        }
      }

      // Social media accounts
      social_accounts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          platform: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id: string
          account_name: string
          access_token: string
          refresh_token: string | null
          token_expires_at: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          platform: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id: string
          account_name: string
          access_token: string
          refresh_token?: string | null
          token_expires_at?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          platform?: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id?: string
          account_name?: string
          access_token?: string
          refresh_token?: string | null
          token_expires_at?: string | null
          is_active?: boolean
        }
      }

      // Content posts
      posts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          content_text: string
          content_images: string[]
          platforms: string[]
          status: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for: string | null
          published_at: string | null
          ai_generated: boolean
          engagement_metrics: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          content_text: string
          content_images?: string[]
          platforms: string[]
          status?: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for?: string | null
          published_at?: string | null
          ai_generated?: boolean
          engagement_metrics?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          content_text?: string
          content_images?: string[]
          platforms?: string[]
          status?: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for?: string | null
          published_at?: string | null
          ai_generated?: boolean
          engagement_metrics?: Json | null
        }
      }

      // n8n workflow executions
      workflow_executions: {
        Row: {
          id: string
          user_id: string
          created_at: string
          workflow_id: string
          workflow_name: string
          status: 'running' | 'completed' | 'failed'
          input_data: Json
          output_data: Json | null
          error: string | null
          started_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          workflow_id: string
          workflow_name: string
          status?: 'running' | 'completed' | 'failed'
          input_data: Json
          output_data?: Json | null
          error?: string | null
          started_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          workflow_id?: string
          workflow_name?: string
          status?: 'running' | 'completed' | 'failed'
          input_data?: Json
          output_data?: Json | null
          error?: string | null
          started_at?: string
          completed_at?: string | null
        }
      }

      // User roles for authorization
      user_roles: {
        Row: {
          id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }
    }

    Views: {
      // Add views here as needed
    }

    Functions: {
      // Add database functions here as needed
    }

    Enums: {
      // Add custom enums here as needed
    }

    CompositeTypes: {
      // Add composite types here as needed
    }
  }
}
