/**
 * Supabase Database Types
 *
 * This file will be auto-generated by the Supabase CLI once the database schema is created.
 * For now, it provides a placeholder type structure for development.
 *
 * To generate actual types after database setup:
 * 1. Install Supabase CLI: npm install -g supabase
 * 2. Login: supabase login
 * 3. Generate types: supabase gen types typescript --project-id [your-project-id] > types/supabase.ts
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      // User profiles extending Supabase auth
      profiles: {
        Row: {
          id: string
          created_at: string
          updated_at: string
          email: string
          full_name: string | null
          avatar_url: string | null
          subscription_tier: 'free' | 'pro' | 'enterprise'
          subscription_status: 'active' | 'inactive' | 'cancelled'
        }
        Insert: {
          id: string
          created_at?: string
          updated_at?: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          subscription_tier?: 'free' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'inactive' | 'cancelled'
        }
        Update: {
          id?: string
          created_at?: string
          updated_at?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          subscription_tier?: 'free' | 'pro' | 'enterprise'
          subscription_status?: 'active' | 'inactive' | 'cancelled'
        }
      }

      // Brand Brain tables
      brands: {
        Row: {
          id: string
          user_id: string
          name: string
          slug: string
          description: string | null
          website_url: string | null
          industry: string | null
          primary_color: string | null
          secondary_color: string | null
          is_active: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          name: string
          slug?: string
          description?: string | null
          website_url?: string | null
          industry?: string | null
          primary_color?: string | null
          secondary_color?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          name?: string
          slug?: string
          description?: string | null
          website_url?: string | null
          industry?: string | null
          primary_color?: string | null
          secondary_color?: string | null
          is_active?: boolean
          created_at?: string
          updated_at?: string
        }
      }

      brand_voice: {
        Row: {
          id: string
          brand_id: string
          tone: string[] | null
          writing_style: string[] | null
          communication_preferences: Json | null
          keywords: string[] | null
          avoid_phrases: string[] | null
          content_themes: string[] | null
          brand_values: string[] | null
          unique_selling_points: string[] | null
          voice_embedding: number[] | null
          embedding_version: number | null
          last_trained_at: string | null
          training_sample_count: number | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          tone?: string[] | null
          writing_style?: string[] | null
          communication_preferences?: Json | null
          keywords?: string[] | null
          avoid_phrases?: string[] | null
          content_themes?: string[] | null
          brand_values?: string[] | null
          unique_selling_points?: string[] | null
          voice_embedding?: number[] | null
          embedding_version?: number | null
          last_trained_at?: string | null
          training_sample_count?: number | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          tone?: string[] | null
          writing_style?: string[] | null
          communication_preferences?: Json | null
          keywords?: string[] | null
          avoid_phrases?: string[] | null
          content_themes?: string[] | null
          brand_values?: string[] | null
          unique_selling_points?: string[] | null
          voice_embedding?: number[] | null
          embedding_version?: number | null
          last_trained_at?: string | null
          training_sample_count?: number | null
          created_at?: string
          updated_at?: string
        }
      }

      brand_content_examples: {
        Row: {
          id: string
          brand_id: string
          content_type: 'post' | 'caption' | 'story' | 'article' | 'email' | 'other'
          platform: string | null
          content_text: string
          content_metadata: Json | null
          embedding: number[] | null
          performance_score: number
          engagement_metrics: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          content_type: 'post' | 'caption' | 'story' | 'article' | 'email' | 'other'
          platform?: string | null
          content_text: string
          content_metadata?: Json | null
          embedding?: number[] | null
          performance_score?: number
          engagement_metrics?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          content_type?: 'post' | 'caption' | 'story' | 'article' | 'email' | 'other'
          platform?: string | null
          content_text?: string
          content_metadata?: Json | null
          embedding?: number[] | null
          performance_score?: number
          engagement_metrics?: Json | null
          created_at?: string
        }
      }

      target_audiences: {
        Row: {
          id: string
          brand_id: string
          name: string
          demographics: Json | null
          interests: string[] | null
          pain_points: string[] | null
          goals: string[] | null
          preferred_platforms: string[] | null
          content_preferences: Json | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          name: string
          demographics?: Json | null
          interests?: string[] | null
          pain_points?: string[] | null
          goals?: string[] | null
          preferred_platforms?: string[] | null
          content_preferences?: Json | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          name?: string
          demographics?: Json | null
          interests?: string[] | null
          pain_points?: string[] | null
          goals?: string[] | null
          preferred_platforms?: string[] | null
          content_preferences?: Json | null
          created_at?: string
          updated_at?: string
        }
      }

      brand_guidelines: {
        Row: {
          id: string
          brand_id: string
          guideline_type: 'visual' | 'content' | 'tone' | 'legal' | 'other'
          title: string
          description: string | null
          rules: Json | null
          examples: string[] | null
          priority: 'critical' | 'high' | 'medium' | 'low'
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          guideline_type: 'visual' | 'content' | 'tone' | 'legal' | 'other'
          title: string
          description?: string | null
          rules?: Json | null
          examples?: string[] | null
          priority?: 'critical' | 'high' | 'medium' | 'low'
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          guideline_type?: 'visual' | 'content' | 'tone' | 'legal' | 'other'
          title?: string
          description?: string | null
          rules?: Json | null
          examples?: string[] | null
          priority?: 'critical' | 'high' | 'medium' | 'low'
          created_at?: string
          updated_at?: string
        }
      }

      brand_learning_history: {
        Row: {
          id: string
          brand_id: string
          learning_type: 'initial_training' | 'content_update' | 'voice_refinement' | 'manual_adjustment'
          training_data: Json | null
          samples_used: number | null
          model_version: string | null
          performance_metrics: Json | null
          created_at: string
        }
        Insert: {
          id?: string
          brand_id: string
          learning_type: 'initial_training' | 'content_update' | 'voice_refinement' | 'manual_adjustment'
          training_data?: Json | null
          samples_used?: number | null
          model_version?: string | null
          performance_metrics?: Json | null
          created_at?: string
        }
        Update: {
          id?: string
          brand_id?: string
          learning_type?: 'initial_training' | 'content_update' | 'voice_refinement' | 'manual_adjustment'
          training_data?: Json | null
          samples_used?: number | null
          model_version?: string | null
          performance_metrics?: Json | null
          created_at?: string
        }
      }

      // Brand Brain context store
      brand_context: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          brand_name: string
          brand_voice: Json
          brand_values: string[]
          target_audience: Json
          content_pillars: string[]
          visual_identity: Json
          competitors: string[]
          unique_selling_points: string[]
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          brand_name: string
          brand_voice?: Json
          brand_values?: string[]
          target_audience?: Json
          content_pillars?: string[]
          visual_identity?: Json
          competitors?: string[]
          unique_selling_points?: string[]
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          brand_name?: string
          brand_voice?: Json
          brand_values?: string[]
          target_audience?: Json
          content_pillars?: string[]
          visual_identity?: Json
          competitors?: string[]
          unique_selling_points?: string[]
        }
      }

      // Social media accounts
      social_accounts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          platform: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id: string
          account_name: string
          access_token: string
          refresh_token: string | null
          token_expires_at: string | null
          is_active: boolean
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          platform: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id: string
          account_name: string
          access_token: string
          refresh_token?: string | null
          token_expires_at?: string | null
          is_active?: boolean
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          platform?: 'instagram' | 'twitter' | 'linkedin' | 'tiktok'
          account_id?: string
          account_name?: string
          access_token?: string
          refresh_token?: string | null
          token_expires_at?: string | null
          is_active?: boolean
        }
      }

      // Content posts
      posts: {
        Row: {
          id: string
          user_id: string
          created_at: string
          updated_at: string
          content_text: string
          content_images: string[]
          platforms: string[]
          status: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for: string | null
          published_at: string | null
          ai_generated: boolean
          engagement_metrics: Json | null
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          updated_at?: string
          content_text: string
          content_images?: string[]
          platforms: string[]
          status?: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for?: string | null
          published_at?: string | null
          ai_generated?: boolean
          engagement_metrics?: Json | null
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          updated_at?: string
          content_text?: string
          content_images?: string[]
          platforms?: string[]
          status?: 'draft' | 'scheduled' | 'published' | 'failed'
          scheduled_for?: string | null
          published_at?: string | null
          ai_generated?: boolean
          engagement_metrics?: Json | null
        }
      }

      // n8n workflow executions
      workflow_executions: {
        Row: {
          id: string
          user_id: string
          created_at: string
          workflow_id: string
          workflow_name: string
          status: 'running' | 'completed' | 'failed'
          input_data: Json
          output_data: Json | null
          error: string | null
          started_at: string
          completed_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          created_at?: string
          workflow_id: string
          workflow_name: string
          status?: 'running' | 'completed' | 'failed'
          input_data: Json
          output_data?: Json | null
          error?: string | null
          started_at?: string
          completed_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          created_at?: string
          workflow_id?: string
          workflow_name?: string
          status?: 'running' | 'completed' | 'failed'
          input_data?: Json
          output_data?: Json | null
          error?: string | null
          started_at?: string
          completed_at?: string | null
        }
      }

      // User roles for authorization
      user_roles: {
        Row: {
          id: string
          user_id: string
          role: string
          created_at: string
        }
        Insert: {
          id?: string
          user_id: string
          role: string
          created_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          role?: string
          created_at?: string
        }
      }
    }

    Views: {
      // Add views here as needed
    }

    Functions: {
      // Vector search functions
      search_similar_voice: {
        Args: {
          query_embedding: number[]
          brand_id_filter: string
          match_threshold: number
          match_count: number
        }
        Returns: Array<{
          id: string
          content_text: string
          similarity: number
          platform: string | null
          performance_score: number
        }>
      }
      search_similar_content: {
        Args: {
          query_embedding: number[]
          brand_id_filter: string
          match_threshold: number
          match_count: number
        }
        Returns: Array<{
          id: string
          content_text: string
          similarity: number
          platform: string | null
          performance_score: number
        }>
      }
      search_global_content: {
        Args: {
          query_embedding: number[]
          user_id_filter: string
          match_threshold: number
          match_count: number
        }
        Returns: Array<{
          id: string
          content_text: string
          similarity: number
          platform: string | null
          performance_score: number
          brand_name: string
        }>
      }
    }

    Enums: {
      // Add custom enums here as needed
    }

    CompositeTypes: {
      // Add composite types here as needed
    }
  }
}
